version: '3.1'
services:
  node:
    build: ./server
    depends_on:
      - mysql
    container_name: "node-container"
  nginx:
    image: nginx:latest
    depends_on:
      - node
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8080:80
    container_name: "ngnix-container"
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'demodb'
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
       - ./db/init:/docker-entrypoint-initdb.d
    container_name: "mysql-container"